spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingdb
  config:
    import: optional:configserver:http://localhost:9000

  application:
    name: RATING-SERVICE

server:
  port: 8086
#
#eureka:
#  instance:
#    prefer-ip-address-: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka